name: Debian Package Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-python python3-distutils-extra

      - name: Create source tarball
        run: |
          VERSION=$(cd epoptes && dpkg-parsechangelog -S Version)
          tar -cJf epoptes_${VERSION}.orig.tar.xz --exclude=.git --transform "s,^,epoptes-${VERSION}/," epoptes

      - name: Verify dependencies
        run: dpkg-checkbuilddeps || true

      - name: Build source package
        run: |
          debuild -S -sa

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: ../*.{deb,tar.xz,dsc,changes}
