name: Build, Lint, and Test Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts lintian dpkg-dev fakeroot python3-distutils-extra
        sudo apt-get build-dep ./ -y

    - name: Zip and Build Debian Package
      run: |
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="epoptes_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix=epoptes/ -o $TARBALL HEAD
        mv $TARBALL ..
        mkdir -p /tmp/debian-package
        cd $GITHUB_WORKSPACE
        debuild -us -uc
        find .. -name "*.deb" -exec mv {} /tmp/debian-package/ \;
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib

    - name: List Directories
      run: |
        ls -al /tmp/debian-package
        ls -al $GITHUB_WORKSPACE

    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: epoptes-deb
        path: /tmp/debian-package/*.deb
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false

    - name: Testing
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Tests
      run: |
        sudo apt-get update
        lintnian --profile debian --fail-on-warnings --fail-on-error --show-info --show-overrides --pedantic /tmp/debian-package/*.deb
        sudo apt-get install --install-recommends -y /tmp/debian-package/*.deb

        ls -all etc/xdg/autostart/
        ls -all usr/sbin/
        ls -all usr/share/epoptes-client/

        ls -all debian/ufw/epoptes etc/ufw/applications.d
        ls -all usr/bin/
        ls -all usr/lib/python*/*/*.egg-info
        ls -all usr/lib/python*/*/epoptes/*/
        ls -all usr/lib/python*/*/epoptes/
        ls -all usr/lib/python*/*/twisted/plugins/
        ls -all usr/share/applications/
        ls -all usr/share/icons/
        ls -all usr/share/locale/
        ls -all usr/share/ltsp/plugins/ltsp-build-client/common/
        ls -all usr/share/epoptes/

        systemctl status epoptes
        systemctl status epoptes-client