name: Build Epoptes and Epoptes-Client Debian Packages

on:
  push:
    branches:
      - main

jobs:
  build-epoptes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts lintian dpkg-dev fakeroot python3-distutils-extra python3-setuptools python3-twisted gettext
        sudo apt-get build-dep ./ -y

    - name: Prepare .po files with gettext
      run: |
        cd po
        for po_file in *.po; do
          lang=$(basename "$po_file" .po)
          mkdir -p ../debian/tmp/usr/share/locale/$lang/LC_MESSAGES
          msgfmt -o ../debian/tmp/usr/share/locale/$lang/LC_MESSAGES/epoptes.mo "$po_file"
        done

    - name: Run setup.py
      run: |
        python3 setup.py build
        python3 setup.py install --root=debian/tmp

    - name: Copy missing files
      run: |
        mkdir -p debian/tmp/usr/bin
        cp bin/epoptes debian/tmp/usr/bin/

    - name: Copy Twisted plugin
      run: |
        mkdir -p debian/tmp/usr/lib/python3/dist-packages/twisted/plugins
        cp twisted/plugins/epoptesd.py debian/tmp/usr/lib/python3/dist-packages/twisted/plugins/

    - name: Create Orig Tarball
      run: |
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="epoptes_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix=epoptes/ -o $TARBALL HEAD
        mv $TARBALL ..

    - name: Build Epoptes Debian Package
      run: |
        mkdir -p /tmp/epoptes-deb
        debuild -us -uc -b
        find .. -name "epoptes*.deb" -exec mv {} /tmp/epoptes-deb/ \;

    - name: Upload Epoptes Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: epoptes-deb
        path: /tmp/epoptes-deb/*.deb
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false

  build-epoptes-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts lintian dpkg-dev fakeroot python3-distutils-extra python3-setuptools python3-twisted gettext
        sudo apt-get build-dep ./ -y

    - name: Prepare .po files with gettext
      run: |
        cd po
        for po_file in *.po; do
          lang=$(basename "$po_file" .po)
          mkdir -p ../debian/tmp/usr/share/locale/$lang/LC_MESSAGES
          msgfmt -o ../debian/tmp/usr/share/locale/$lang/LC_MESSAGES/epoptes-client.mo "$po_file"
        done

    - name: Run setup.py
      run: |
        python3 setup.py build
        python3 setup.py install --root=debian/tmp

    - name: Create Orig Tarball
      run: |
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="epoptes-client_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix=epoptes-client/ -o $TARBALL HEAD
        mv $TARBALL ..

    - name: Build Epoptes-Client Debian Package
      run: |
        mkdir -p /tmp/epoptes-client-deb
        debuild -us -uc -b
        find .. -name "epoptes-client*.deb" -exec mv {} /tmp/epoptes-client-deb/ \;

    - name: Upload Epoptes-Client Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: epoptes-client-deb
        path: /tmp/epoptes-client-deb/*.deb
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false

  test-packages:
    runs-on: ubuntu-latest
    needs: [build-epoptes, build-epoptes-client]

    steps:
      - name: Download Epoptes Package
        uses: actions/download-artifact@v4
        with:
          name: epoptes-deb
          path: /tmp/epoptes-deb/

      - name: Download Epoptes-Client Package
        uses: actions/download-artifact@v4
        with:
          name: epoptes-client-deb
          path: /tmp/epoptes-client-deb/

      - name: Install and Test Packages
        run: |
          sudo apt-get update
          sudo apt-get install --install-recommends -y /tmp/epoptes-deb/*.deb
          sudo apt-get install --install-recommends -y /tmp/epoptes-client-deb/*.deb

          ls -all etc/xdg/autostart/
          ls -all usr/sbin/
          ls -all usr/share/epoptes-client/

          ls -all debian/ufw/epoptes etc/ufw/applications.d
          ls -all usr/bin/
          ls -all usr/lib/python*/*/*.egg-info
          ls -all usr/lib/python*/*/epoptes/*/
          ls -all usr/lib/python*/*/epoptes/
          ls -all usr/lib/python*/*/twisted/plugins/
          ls -all usr/share/applications/
          ls -all usr/share/icons/
          ls -all usr/share/locale/
          ls -all usr/share/ltsp/plugins/ltsp-build-client/common/
          ls -all usr/share/epoptes/

          systemctl status epoptes
          systemctl status epoptes-client