name: Build and Test Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts lintian dpkg-dev fakeroot python3-distutils-extra
        sudo apt-get build-dep ./ -y

    - name: Create source tarball
      run: |
        VERSION=$(dpkg-parsechangelog --show-field Version)
        tar -cJf ../epoptes_${VERSION}.orig.tar.xz .
      working-directory: .

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: '../*.deb'

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Debian package
      uses: actions/download-artifact@v4
      with:
        name: debian-package

    - name: Install runtime dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y adduser faketime gir1.2-gtk-3.0 gir1.2-notify-0.7 iperf iproute2 librsvg2-common notification-daemon openssl python3-dbus python3-gi python3-gi-cairo python3-netifaces python3-openssl python3-twisted xvnc4viewer socat x11vnc xterm

    - name: Install Debian package
      run: |
        sudo dpkg -i epoptes*.deb

    - name: Run lintian checks
      run: |
        lintian epoptes*.deb

    - name: Check package installation
      run: |
        dpkg -l | grep epoptes

    - name: Run tests
      run: |
        pytest
        systemctl status epoptes
